version: '2'
services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - /website/anniversary:/usr/share/nginx/html:ro
    - /website/anniversary/nginx.conf:/etc/nginx/nginx.conf:ro
